import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/context/ThemeContext";
import ThemeWrapper from "@/context/ThemeWrapper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Weather App",
	description: "Generated by create next app",
};

export default function RootLayout({
	section1,
	section2,
}: Readonly<{
	section1: React.ReactNode;
	section2: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider>
					<ThemeWrapper>
						<div
							className={`bg-slate-800 w-full h-screen flex items-center justify-center`}>
							<div className="w-[70%] h-[80%] p-5 rounded-[30px] glass flex items-center">
								<div className="w-[30%] h-full">{section1}</div>
								<div className="w-[70%] h-full">{section2}</div>
							</div>
						</div>
					</ThemeWrapper>
				</ThemeProvider>
			</body>
		</html>
	);
}
